[bs4]
filename = bs4.py
python.version = python3
python.required = 3.9, 3.13
chunked = true

[cleantext]
filename = cleantext.py
python.version = python3
python.required = 3.9, 3.13
chunked = true

[similarity]
filename = similarity.py
python.version = python3
python.required = 3.9, 3.13
chunked = true

[vader]
filename = vader.py
python.version = python3
python.required = 3.9, 3.13
chunked = true
